### ISSUE TITLE
Environment Secrets only 50 characters long?

### ISSUE THREAD

**Issue by tobkle** [daytonaio/enterprise-docs#99]
**Describe the bug**
Environment Secret Value  has a maximum of 50 characters only?
Cannot add many of my secret values, they are all longer.
Or is the intention that I have to use something like Doppler?

**To Reproduce**
1. Go to 'Dashboard: Env Variables"
2. Enter Secret Value
3. Only the first 50 characters are stored
4. That is too short to host my secrets here.

**Expected behavior**
Secret Value Fields to accept longer values.

**Desktop (please complete the following information):**
 - OS: Ubuntu 24
 - Daytona Version: current https://github.com/daytonaio/enterprise-demo/setup.sh 
   Do not see any version tags anywhere.

**Comment by Tpuljak** [comment]
@tobkle thanks for raising the issue.

Because the “daytona” repo is not associated with the enterprise version of Daytona (which is not open source), I’ve moved the issue here.

tagging @fabjanvucina who can take a look

**Comment by fabjanvucina** [comment]
@tobkle Thank you for pointing out this issue. We will resolve it in one of the upcoming releases!

Since this is a repo for the enterprise docs, I will close this issue in favor of #93. All conventions and limitations regarding environment variables will be written out in the relevant docs section.
